services:
  api:
    build:
      context: ./src/PortfolioTracker.Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__Default=Host=postgres;Database=portfolio;Username=postgres;Password=postgres
      - TwelveDataApiKey=b3e8bc7134ad402ab64b7bc6585c4023
      - FmpApiKey=nOC6v8vCcvbsTKb1lk4Dz8Vak0lP3XrS
      - EodApiKey=6a7906fedfbc20.46232573
    networks:
      - portfolio-network

  blazor:
    build:
      context: ./src/PortfolioTracker.Blazor
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiBaseUrl=http://api:8080
    networks:
      - portfolio-network

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=portfolio
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - portfolio-network

volumes:
  postgres_data:

networks:
  portfolio-network:
    driver: bridge
